
package views;

import data.Persistencia;
import domain.VehiculoTipo;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

public class IngresarVehiculoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresarVehiculoView.class.getName());
    
    public IngresarVehiculoView() {
        initComponents();
        cargarComboSucursales();
        cargarComboMarcas();
        
        botonRegistrar.addActionListener(evt -> {
            RegistrarVehiculoActionPerformed(evt);
        });
        botonCancelar.addActionListener(evt -> {
            CancelarActionPerformed(evt);
        });
        comboMarcas.addActionListener(evt -> {
            ComboMarcasItemSelected(evt);
        });
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoModelo = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        campoAnio = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        campoCapacidadCarga = new javax.swing.JTextField();
        lblCapacidadCarga = new javax.swing.JLabel();
        labelSucursal = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        panelColor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboMarcas = new javax.swing.JComboBox<>();
        lblMarca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelPaisMarca = new javax.swing.JLabel();
        comboSucursal = new javax.swing.JComboBox<>();
        tabsTiposVehiculos = new javax.swing.JTabbedPane(){
            @Override
            public boolean isFocusable() {
                return false; // Evita que se pueda navegar con las flechas del teclado
            }
        };
        jPanel1 = new javax.swing.JPanel();
        labelKmPorLitro = new javax.swing.JLabel();
        campoKmPorLitro = new javax.swing.JTextField();
        labelLitrosExtra = new javax.swing.JLabel();
        campoLitrosExtra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelKWHporHora = new javax.swing.JLabel();
        campoKWporHora = new javax.swing.JTextField();
        lblPatente = new javax.swing.JLabel();
        campoPatente = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logística - Registrar Vehículo");
        setResizable(false);
        setSize(new java.awt.Dimension(652, 311));

        campoModelo.setPreferredSize(new java.awt.Dimension(150, 20));

        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelo.setText("Modelo");
        lblModelo.setPreferredSize(new java.awt.Dimension(97, 14));

        campoAnio.setPreferredSize(new java.awt.Dimension(150, 20));

        lblAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnio.setText("Año");
        lblAnio.setPreferredSize(new java.awt.Dimension(97, 14));

        campoCapacidadCarga.setPreferredSize(new java.awt.Dimension(150, 20));

        lblCapacidadCarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapacidadCarga.setText("Capacidad de Carga");

        labelSucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSucursal.setText("Sucursal");

        panelContenedor.setLayout(new java.awt.CardLayout());

        botonCancelar.setText("Cancelar");

        panelColor.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Nuevo Vehículo");

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboMarcas.setPreferredSize(new java.awt.Dimension(150, 24));
        comboMarcas.setRequestFocusEnabled(false);

        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarca.setText("Marca");
        lblMarca.setPreferredSize(new java.awt.Dimension(97, 14));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("País");
        jLabel2.setPreferredSize(new java.awt.Dimension(97, 14));

        labelPaisMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPaisMarca.setText("...");
        labelPaisMarca.setPreferredSize(new java.awt.Dimension(150, 14));

        labelKmPorLitro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKmPorLitro.setText("Km. por Litro");

        campoKmPorLitro.setToolTipText("");

        labelLitrosExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLitrosExtra.setText("Litros Extra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelLitrosExtra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelKmPorLitro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoKmPorLitro)
                    .addComponent(campoLitrosExtra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoKmPorLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKmPorLitro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLitrosExtra)
                    .addComponent(campoLitrosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        tabsTiposVehiculos.addTab("Combustible", jPanel1);

        labelKWHporHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKWHporHora.setText("kW por Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelKWHporHora, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoKWporHora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoKWporHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKWHporHora))
                .addGap(0, 86, Short.MAX_VALUE))
        );

        tabsTiposVehiculos.addTab("Eléctrico", jPanel2);

        lblPatente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatente.setText("Patente");
        lblPatente.setPreferredSize(new java.awt.Dimension(97, 14));

        campoPatente.setPreferredSize(new java.awt.Dimension(150, 20));

        botonRegistrar.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCapacidadCarga, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPatente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoPatente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoCapacidadCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPaisMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMarcas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tabsTiposVehiculos))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSucursal))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tabsTiposVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(labelPaisMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCapacidadCarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarVehiculoActionPerformed(ActionEvent evt){

        if (ValidarCompletos()) {
            String modelo = campoModelo.getText();
            String anio = campoAnio.getText();
            String capacidad = campoCapacidadCarga.getText();
            String patente = campoPatente.getText();

            String marca = comboMarcas.getSelectedItem().toString();
            String[] sucursalSelPartes = comboSucursal.getSelectedItem().toString().split(" - ");
            String sucursal = sucursalSelPartes[0];

            boolean resultado = false;

            switch (tabsTiposVehiculos.getSelectedIndex()) {
                case 0:
                    String kmPorLitro = campoKmPorLitro.getText();
                    String litrosExtra = campoLitrosExtra.getText();
                    resultado = Controlador.registrarVehiculoCombustible(
                            marca, modelo, anio,
                            capacidad, patente, sucursal,
                            kmPorLitro, litrosExtra
                    );
                    break;
                case 1:
                    String kwh = campoKWporHora.getText();
                    resultado = Controlador.registrarVehiculoElectrico(
                            marca, modelo, anio,
                            capacidad, patente, sucursal,
                            kwh
                    );
                    break;
            }
            if (resultado) {
                MostrarExito();
                Controlador.NavegarMenuPrincipal();
                this.dispose();
            }
        }
    }
    
    private void CancelarActionPerformed(ActionEvent evt){
        Controlador.NavegarMenuPrincipal();
        this.dispose();
    }
    
    private void ComboMarcasItemSelected(ActionEvent evt){
        if (comboMarcas.getSelectedItem() != null) {
            String marca = comboMarcas.getSelectedItem().toString();
            MarcaViewModel marcaSel = Controlador.getMarca(marca);
            labelPaisMarca.setText(marcaSel.getPais());
        }
    }
    
    private void cargarComboSucursales(){
        comboSucursal.removeAllItems();
        ArrayList<SucursalViewModel> sucursales = Controlador.getSucursales();
        for(SucursalViewModel sucursal : sucursales){
            comboSucursal.addItem(sucursal.getCodigo() + " - " 
                                  + sucursal.getCiudad() + " - "
                                  + sucursal.getDireccion());
        }
        comboSucursal.setSelectedIndex(-1);
    }
    
    private void cargarComboMarcas(){
        comboMarcas.removeAllItems();
        ArrayList<MarcaViewModel> marcas = Controlador.getMarcas();
        for(MarcaViewModel marca : marcas){
            comboMarcas.addItem(marca.getMarcaNombre());
        }
        comboMarcas.setSelectedIndex(-1);
    }
    
    private boolean ValidarCompletos(){
        if (comboMarcas.getSelectedIndex() == -1 
                || campoModelo.getText().trim().isEmpty()
                || campoAnio.getText().trim().isEmpty()) {
            MostrarError("Por favor, complete la Marca, el Modelo y Año.");
            return false;
        }
        if(comboSucursal.getSelectedIndex() == -1){
            MostrarError("Por favor, seleccione la sucursal a la que corresponde.");
            return false;
        }
        if(tabsTiposVehiculos.getSelectedIndex() == 0){
            if(campoKmPorLitro.getText().trim().isEmpty()
                    || campoLitrosExtra.getText().trim().isEmpty()){
            MostrarError("Por favor, complete datos de consumo de combustible.");
            return false;
            }
        }
        if(tabsTiposVehiculos.getSelectedIndex() == 1
                && campoKWporHora.getText().trim().isEmpty()){
            MostrarError("Por favor, complete datos de consumo eléctrico.");
            return false;
        }
        if(campoCapacidadCarga.getText().trim().isEmpty()){
            MostrarError("Por favor, complete capacidad de carga.");
            return false;
        }
        if(campoPatente.getText().trim().isEmpty()){
            MostrarError("Por favor, complete patente del vehículo.");
            return false;
        }
        return true;
    }
    
    private void MostrarExito(){
        javax.swing.JOptionPane.showMessageDialog(null,
        "El vehículo se ha registrado con éxito", 
        "Registro de Vehículo", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    public static void MostrarError(String mensaje){
        javax.swing.JOptionPane.showMessageDialog(null,
        mensaje, 
        "Error de Validación de Datos", 
        javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresarVehiculoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoAnio;
    private javax.swing.JTextField campoCapacidadCarga;
    private javax.swing.JTextField campoKWporHora;
    private javax.swing.JTextField campoKmPorLitro;
    private javax.swing.JTextField campoLitrosExtra;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextField campoPatente;
    private javax.swing.JComboBox<String> comboMarcas;
    private javax.swing.JComboBox<String> comboSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelKWHporHora;
    private javax.swing.JLabel labelKmPorLitro;
    private javax.swing.JLabel labelLitrosExtra;
    private javax.swing.JLabel labelPaisMarca;
    private javax.swing.JLabel labelSucursal;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblCapacidadCarga;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JTabbedPane tabsTiposVehiculos;
    // End of variables declaration//GEN-END:variables
}
